[package]
name = "sagan-render"
version = "0.5.1"
source = "src"
entry = "window"

[native]
__render_ui_mesh_sphere = "(Float64, Float64, Float64, Float64, Float64<meter>, Float64<meter>, Float64<meter>, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Int64, Float64, Bool) -> Void"
