[package]
name = "sagan-render"
version = "0.5.1"
source = "src"
entry = "window"

[native]
__render_ui_mesh_sphere = "(Float64, Float64, Float64, Float64, Float64<meter>, Float64<meter>, Float64<meter>, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Float64<meter>, Int64, Float64, Bool) -> Void"
__render_ui_line = "(Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Int64, Int64) -> Void"
__render_ui_orbit_delta_x = "() -> Float64"
__render_ui_orbit_delta_y = "() -> Float64"
__render_ui_scroll_y = "() -> Float64"
